### ISSUE TITLE
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

### ISSUE THREAD

**Issue by mcgregol** [zadewg/Election-Meddling#2]
First off, I must say that I am intrigued by this repo.  Nice work! Generating a diagram showing a Twitter user's political views with AI is very cool.  Just one question though, when I run the script, I get `Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.`  I am a beginner programmer and don't really understand why I am getting this or its purpose but this project interests me so much that I had to ask.

Thanks

**Comment by zadewg** [comment]
Hi - sorry for the huge delay, not sure how this went unnoticed. For that error simply upgrade matplotlib to the latest version: `pip install -U matplotlib`. I recon after this long time the twitter crawler might need some tweaking though, do feel free to reach me on telegram if you want me to help you with it. Cheers
